SELECT 
    X AS FUND_KEY,
    UNIQUE_SECURITY_ID AS SECURITY_KEY,
    X AS CHILD_FUND_ID,
    LOC_CURRENCY AS CURRENCY_KEY,
    X AS DATE_KEY,
    X AS DATA_SOURCE_ID,
    X AS EXTERNAL_HOLDING_ID,
    MNTHLY_PERF_EST_METHOD AS MONTHLY_PERF_EST_METHOD,
    INVESTMENT_VALUE_EST_METHOD AS INVESTMENT_VALUE_EST_METHOD,
    COUPON_RATE AS COUPON_RATE,
    MATURITY_DATE AS MATURITY_DATE,
    X AS UNIT_AMOUNT,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO,
    SOURCE_FILENAME AS LINEAGEKEY

FROM {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}
JOIN {{ ref('FUND_DIM') }} ON {{ ref('FUND_DIM') }}.FUND_KEY = {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.X