SELECT
    SEQ4()+1 CURRENCY_PAIR_KEY,
    A.CURRENCY_CODE AS SOURCE_CURRENCY_KEY,
    B.CURRENCY_CODE AS TARGET_CURRENCY_KEY,
    CONCAT (A.CURRENCY_CODE, B.CURRENCY_CODE)AS PAIR_NAME
FROM
  {{ ref('CURRENCY_DIM') }} A,
  {{ ref('CURRENCY_DIM') }} B