WITH GENERATED_ROWS AS (
  SELECT SEQ4() DAYS_BCK
    FROM TABLE(GENERATOR(ROWCOUNT => 10000)) 
)

SELECT
    DATEADD(DAY, DAYS_BCK * -1, CURRENT_DATE()) AS FULL_DATE
    ,TO_VARCHAR(FULL_DATE,'YYYYMMDD')::INT AS DATE_KEY
    ,DATE_PART(YEAR, FULL_DATE) YEAH
    ,DATE_PART(MONTH, FULL_DATE) MONTH
    ,DATE_PART(DAY, FULL_DATE) DAY_OF_MONTH
    ,DATE_PART(DAYOFYEAR, FULL_DATE) DAY_OF_YEAR
    ,DATE_PART(DAYOFWEEK, FULL_DATE) DAY_OF_WEEK
    ,FLOOR((DAY_OF_MONTH - 1) / 7) + 1 AS WEEK_OF_MONTH
    ,DATE_PART(WEEKOFYEAR, FULL_DATE) WEEK_OF_YEAR
    ,DATE_PART(QUARTER, FULL_DATE) QUARTER
    ,DAYNAME(FULL_DATE) AS DAY_NAME
    ,MONTHNAME(FULL_DATE) AS MONTH_NAME
    ,CASE
        WHEN DAY_OF_WEEK IN (0,6) THEN TRUE
        ELSE FALSE
     END AS IS_WEEKEND
    ,CASE
        WHEN MONTH = 1 AND DAY_OF_MONTH = 1 THEN TRUE -- New Years
        WHEN MONTH = 1 AND DAY_OF_WEEK = 1 AND WEEK_OF_MONTH = 3 THEN TRUE -- MLK
        WHEN MONTH = 2 AND DAY_OF_WEEK = 1 AND WEEK_OF_MONTH = 3 THEN TRUE -- Presidents
        WHEN MONTH = 5 AND DAY_OF_WEEK = 1 AND WEEK_OF_MONTH = 4 THEN TRUE -- Memorial
        WHEN MONTH = 7 AND DAY_OF_MONTH = 4 THEN TRUE -- Independence
        WHEN MONTH = 9 AND DAY_OF_WEEK = 1 AND WEEK_OF_MONTH = 1 THEN TRUE -- Labor
        WHEN MONTH = 10 AND DAY_OF_WEEK = 1 AND WEEK_OF_MONTH = 2 THEN TRUE -- Columbus
        WHEN MONTH = 11 AND DAY_OF_MONTH = 11 THEN TRUE -- Veterans
        WHEN MONTH = 11 AND DAY_OF_WEEK = 4 AND WEEK_OF_MONTH = 4 THEN TRUE -- Thanksgiving
        WHEN MONTH = 12 AND DAY_OF_MONTH = 25 THEN TRUE -- Christmas
        ELSE FALSE
     END AS IS_HOLIDAY
    
FROM GENERATED_ROWS