
SELECT
    PRIMARY_KEY AS FUND_KEY,
    {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_KEY,
    {{ ref('CLIENT_DIM') }}.CLIENT_KEY,
    {{ ref('CURRENCY_DIM') }}.CURRENCY_KEY,
    {{ ref('FUND_TYPE_DIM') }}.FUND_TYPE_KEY,
    {{ ref('FUND_STATUS_DIM') }}.FUND_STATUS_KEY,
    ENTITY_CODE AS EXTERNAL_FUND_ID,
    ENTITY_NAME AS FUND_NAME,
    ENTITY_SHORT_NAME AS FUND_SHORT_NAME,
    MNTHLY_PERF_EST_METHOD AS MONTHLY_PERF_EST_METHOD,
    INCEPTION_DATE AS INCEPTION_DATE,
    ENTITY_VALUE_EST_METHOD AS ENTITY_VALUE_EST_METHOD,
    COMMINGLED_FLG,
    DAILY_PERF_FLG,
    DAILY_PERF_CNVRSN_DT AS DAILY_PERF_CONVERSION_DATE,
    CLOSE_DATE_PERFORMANCE AS PERF_CLOSE_DATE,
    INCEPTION_DT_GASB,
    FISCAL_YEAR_END_MNTH,
    SOURCE_FILENAME AS LINEAGEKEY,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO

FROM {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}
JOIN {{ ref('DATA_SOURCE_DIM') }} ON {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_NAME = 'STATESTREET'
JOIN {{ ref('CLIENT_DIM') }} ON {{ ref('CLIENT_DIM') }}.NAME = {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}.SPONSOR_ID
JOIN {{ ref('CURRENCY_DIM') }} ON {{ ref('CURRENCY_DIM') }}.CURRENCY_CODE = {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}.CURRENCY_BASE_CODE
JOIN {{ ref('FUND_STATUS_DIM') }} ON {{ ref('FUND_STATUS_DIM') }}.FUND_STATUS_NAME = {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}.ENTITY_STATUS_CODE
JOIN {{ ref('FUND_TYPE_DIM') }} ON {{ ref('FUND_TYPE_DIM') }}.FUND_TYPE_NAME = {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}.SPECIAL_ENTITY_TYPE
WHERE {{ ref('FUND_TYPE_DIM') }}.FUND_TYPE_KEY = 1