SELECT
    PRIMARY_KEY AS INDEX_KEY,
    {{ ref('INDEX_TYPE_DIM') }}.INDEX_TYPE_KEY AS INDEX_TYPE_KEY,
    {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_KEY AS DATA_SOURCE_ID,
    ENTITY_CODE AS EXTERNAL_INDEX_ID,
    ENTITY_NAME AS INDEX_NAME,
    ENTITY_SHORT_NAME AS INDEX_SHORT_NAME,
    SOURCE_FILENAME AS LINEAGEKEY,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO
FROM {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}
JOIN {{ ref('DATA_SOURCE_DIM') }} ON {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_NAME = 'STATESTREET'
JOIN {{ ref('INDEX_TYPE_DIM') }} ON {{ ref('INDEX_TYPE_DIM') }}.INDEX_TYPE_NAME = {{ ref('ACCOUNTPROFILE_SNAPSHOT') }}.SPECIAL_ENTITY_TYPE --compare on similar text case?
WHERE {{ ref('INDEX_TYPE_DIM') }}.INDEX_TYPE_KEY = 1