SELECT
    PRIMARY_KEY AS SECURITY_KEY,
    {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_KEY AS DATA_SOURCE_ID,
    {{ ref('ISSUER_DIM')}}.ISSUER_KEY AS ISSUER_KEY,
    {{ ref('SECURITY_TYPE_DIM')}}.SECURITY_TYPE_KEY AS SECURITY_TYPE_KEY,
    CURRENCY_1.CURRENCY_KEY AS CURRENCY_TRADE_KEY,
    CURRENCY_2.CURRENCY_KEY AS CURRENCY_INCOME_KEY,
    COUNTRY_1.COUNTRY_KEY AS INCORPORATED_COUNTRY_KEY,
    COUNTRY_2.COUNTRY_KEY AS ISSUER_COUNTRY_KEY,
    COUNTRY_3.COUNTRY_KEY AS TRADE_COUNTRY_KEY,
    COUNTRY_3.COUNTRY_KEY AS COUNTRY_NRA_TAX_key,
    {{ ref('EXCHANGE_DIM') }}.EXCHANGE_KEY AS EXCHANGE_KEY,
    NULL AS SOLOVIS_SEC_MASTER_ID,
    UNIQUE_SECURITY_ID AS EXTERNAL_SECURITY_ID,
    ISSUE_SHORT_NAME AS SECURITY_SHORT_NAME,
    ISSUE_LONG_NAME AS SECURITY_LONG_NAME,
    ISSUE_DESCRIPTION_NAME AS SECURITY_DESCRIPTION,
    SECURITY_GROUP_CODE AS SECURITY_GROUP_CODE,
    ISIN_IDENTIFIER AS ISIN,
    SEDOL_IDENTIFIER AS SEDOL,
    BLOOMBERG_IDENTIFIER AS BLOOMBERG_ID,
    MATURITY_DATE AS MATURITY_DATE,
    COUPON_RATE AS COUPON_RATE,
    CALL_PUT_IDENTIFIER AS CALL_PUT_ID,
    SOURCE_FILENAME AS LINEAGEKEY,
    NULL AS EXCHANGE_ID,
    MULTIPLIER_CURRENT_NUMBER AS MULTIPLIER_NUMBER,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO
FROM
    {{ ref('SECURITY_SNAPSHOT') }}
    JOIN {{ ref('DATA_SOURCE_DIM') }} ON {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_NAME = 'STATESTREET'
    JOIN {{ ref('ISSUER_DIM') }} ON {{ ref('ISSUER_DIM') }}.ISSUER_NAME IS NULL
    JOIN {{ ref('SECURITY_TYPE_DIM') }} ON {{ ref('SECURITY_TYPE_DIM') }}.SECURITY_TYPE_CODE = {{ ref('SECURITY_SNAPSHOT') }}.SECURITY_TYPE_CODE
    JOIN {{ ref('CURRENCY_DIM') }} CURRENCY_1 ON CURRENCY_1.CURRENCY_CODE = {{ ref('SECURITY_SNAPSHOT') }}.CURRENCY_TRADE_CODE
    JOIN {{ ref('CURRENCY_DIM') }} CURRENCY_2 ON CURRENCY_2.CURRENCY_CODE = {{ ref('SECURITY_SNAPSHOT') }}.CURRENCY_INCOME_CODE
    JOIN {{ ref('COUNTRY_DIM') }} COUNTRY_1 ON COUNTRY_1.COUNTRY_ISO_CODE_2 = {{ ref('SECURITY_SNAPSHOT') }}.COUNTRY_INCORPORATED_CODE
    JOIN {{ ref('COUNTRY_DIM') }} COUNTRY_2 ON COUNTRY_2.COUNTRY_ISO_CODE_2 = {{ ref('SECURITY_SNAPSHOT') }}.COUNTRY_ISSUE_CODE
    JOIN {{ ref('COUNTRY_DIM') }} COUNTRY_3 ON COUNTRY_3.COUNTRY_ISO_CODE_2 = {{ ref('SECURITY_SNAPSHOT') }}.COUNTRY_TRADE_CODE
    JOIN {{ ref('COUNTRY_DIM') }} COUNTRY_4 ON COUNTRY_4.COUNTRY_ISO_CODE_2 = {{ ref('SECURITY_SNAPSHOT') }}.COUNTRY_NRA_TAX_CODE
    JOIN {{ ref('EXCHANGE_DIM') }} ON {{ ref('EXCHANGE_DIM') }}.EXCHANGE_NAME IS NULL
