
SELECT 
    PRIMARY_KEY AS FUND_HOLDING_KEY,
    {{ ref('FUND_DIM') }}.FUND_KEY,
    {{ ref('SECURITY_DIM') }}.SECURITY_KEY,
    NULL AS CHILD_FUND_ID,
    {{ ref('CURRENCY_DIM') }}.CURRENCY_KEY,
    --date key?
    {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_KEY,
    {{ ref('FUND_DIM') }}.EXTERNAL_FUND_ID,
    MNTHLY_PERF_EST_METHOD,
    INVESTMENT_VALUE_EST_METHOD,
    {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.COUPON_RATE,
    {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.MATURITY_DATE,
    NULL AS UNIT_AMOUNT,
    SOURCE_FILENAME AS LINEAGEKEY,
    DBT_VALID_FROM AS VALIDFROM,
    DBT_VALID_TO AS VALIDTO

FROM {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}
JOIN {{ ref('CURRENCY_DIM') }} ON {{ ref('CURRENCY_DIM') }}.CURRENCY_CODE = {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.LOC_CURRENCY
JOIN {{ ref('DATA_SOURCE_DIM') }} ON {{ ref('DATA_SOURCE_DIM') }}.DATA_SOURCE_NAME = 'STATESTREET'
JOIN {{ ref('FUND_DIM') }} ON {{ ref('FUND_DIM') }}.EXTERNAL_FUND_ID = {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.ENTITY_CODE
JOIN {{ ref('SECURITY_DIM') }} ON {{ ref('SECURITY_DIM') }}.EXTERNAL_SECURITY_ID = {{ ref('ACCOUNTSECURITIES_SNAPSHOT') }}.UNIQUE_SECURITY_ID